In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('medical_insurance.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [3]:
null_counts = dataset.isnull().sum()
print(null_counts)

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64


In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[1,4,5])],remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [5]:
from sklearn.model_selection import train_test_split
X_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state = 1)



In [6]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [7]:
pred = reg.predict(x_test)

In [16]:
print(np.concatenate((pred.reshape(len(pred), 1), y_test.reshape(len(y_test), 1)), axis=1))
Xxz = np.array(X_train)
np.set_printoptions(threshold=np.inf)
print(Xxz)

[[33647.90467522 40419.0191    ]
 [ 1935.66443611  3077.0955    ]
 [ 8414.1908081   6238.298     ]
 ...
 [37947.54958114 52590.82939   ]
 [ 7962.23891959  3238.4357    ]
 [31046.31304385 20149.3229    ]]
[[1.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 60 30.5 0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 63 21.66 0]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 0.0 18 25.46 0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 56 33.82 2]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 18 40.26 0]
 [0.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 22 34.8 3]
 [0.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 62 21.4 0]
 [0.0 1.0 1.0 0.0 0.0 1.0 0.0 0.0 46 40.375 2]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 19 24.51 1]
 [0.0 1.0 1.0 0.0 0.0 0.0 1.0 0.0 48 37.29 2]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 51 37.73 1]
 [0.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 27 45.9 2]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 59 23.655 0]
 [0.0 1.0 0.0 1.0 0.0 0.0 0.0 1.0 31 36.3 2]
 [0.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 24 23.4 0]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 0.0 54 32.775 0]
 [1.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 39 32.8 0]
 [1.0 0.0 1.0 0.0 

In [17]:
print(reg.predict([[0, 1, 1, 0, 0, 0,1,0,57,27.94,1]]))

[11591.63704707]
